serve:
<<<<<<< HEAD
  image: netw0rm/zab:2.4
=======
  image: netw0rm/zab:dev
>>>>>>> 355704d7d2673c4d67cd5c0f96acc6fed99e928d
  container_name: zabbix-serve
  ports:
    - "80:80"
    - "10051:10051"
  volumes:
    - /var/lib/docker/vfs/dir/zab3_alscripts:/usr/local/share/zabbix/alertscripts
    - /var/lib/docker/vfs/dir/zab3_exscripts:/usr/local/share/zabbix/externalscripts
  environment:
    ZS_DBHost: db
    ZS_DBUser: admin
    ZS_DBPassword: mypass
  links:
    - db
  restart: always
db:
  image: zabbix/zabbix-db-mariadb
  container_name: zabbix-db
  volumes:
    - /var/lib/docker/vfs/dir/zab3_db_backups:/backups
    - /var/lib/docker/vfs/dir/zab3_db:/var/lib/mysql
  environment:
    MARIADB_USER: admin
    MARIADB_PASS: mypass
  restart: always
